### ISSUE TITLE
Would you or anybody else be interested in helping out with Restbed?

### ISSUE THREAD

**Issue by ben-crowhurst** [datasift/served#12]
**Tagline:** The [Restbed](https://github.com/corvusoft/restbed) framework brings asynchronous RESTful functionality to C++11 applications.

It's a little bit further down the development road than Served and quite feature rich.  Our aim is to bring HTTP 2 functionality with the ability to introduce additional HTTP protocols via dependency injection. e.g

```
Service service;
service.add_protocol( "HTTP/2", instance );
service.add_protocol( "SPDY", instance );
```

**Comment by KrishnaPG** [comment]
Its license AGPL is not so welcoming.
