### ISSUE TITLE
Curl (7)  Failed to connect

### ISSUE THREAD

**Issue by leoul16** [datasift/served#17]
I am trying to get the hang of served so I downloaded the sample hello world from here https://github.com/datasift/served/tree/master/src/examples/hello_world .
I built using the CMakeLists.txt and every curl attempt I make is giving me a curl (7) error. I am running this on OS X El Capitan. Any ideas on how to fix this?
![screen shot 2016-08-02 at 11 57 53 am](https://cloud.githubusercontent.com/assets/7416281/17335652/afb26d24-58a8-11e6-861f-29eb884d17cc.png)
![screen shot 2016-08-02 at 11 57 36 am](https://cloud.githubusercontent.com/assets/7416281/17335656/b1811254-58a8-11e6-916b-b74f83beaeef.png)

**Comment by Jeffail** [comment]
Hey @leoul16, what command are you using the run the example binary? It doesn't show up in the output you posted.

**Comment by leoul16** [comment]
I thought the MakeFile would make and deploy the binary. What command should I be using?

**Comment by blockchaindev** [comment]
@leoul16 Here's what I did from a fresh git clone:
```bash
$ brew install re2
$ mkdir build && cd build
$ cmake ../
$ make build && make test
$ ../bin/eg_hello_world
$ curl http://localhost:8123/hello
```
Can you do a fresh clone and try the same steps please?

**Comment by blockchaindev** [comment]
@Jeffail I'm pretty sure this is just user error.
