### ISSUE TITLE
Support PATCH Method

### ISSUE THREAD

**Issue by xoox** [datasift/served#23]
Hi, would you please consider to add support for the PATCH method?
PATCH method is used commonly in RESTful APIs of GitHub, Google et.al.
It would be nice for served to support it.

### References
1. [RFC5789 - PATCH Method for HTTP](https://tools.ietf.org/html/rfc5789)

**Comment by Jeffail** [comment]
Done https://github.com/datasift/served/commit/ed112b6f8b894146579b45a6b1586dbc9a5e0317
