### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [datasift/served#29]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by Fihtangolz** [comment]
Conan it is another piece of ****. What's the difference than build if it is not going out of the cmake.

**Comment by ZaMaZaN4iK** [comment]
Because with Conan I can simply run `conan install` command and this library will be integrated into my script (it can be Cmake, xcode, vs solution, whatever else). Wihtout any pain with manual building, writing manually include paths, etc.

**Comment by Fihtangolz** [comment]
There is one thing, but a damn conan may not contain other libs or something else. I probably it, the only application of this crap - windows. By the way, how is the fuzzy search?

**Comment by Jeffail** [comment]
Hey @ZaMaZaN4iK, I'm struggling to keep up with the build systems already in place, I'm going to be focusing on the bazel builds in future as my time on this project is limited but thanks for the suggestion.
